/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "PaymentQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "PaymentQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WalletApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "WalletWebhook": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "payments": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "queueProcessor": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "streamProcessor": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "wallet": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}